version: 0.2.{build}
image:
  - Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:/Python35-x64"
      TARGET: x86_64-pc-windows-msvc

    - PYTHON: "C:/Python36-x64"
      TARGET: x86_64-pc-windows-msvc

    - PYTHON: "C:/Python35"
      TARGET: i686-pc-windows-msvc

    - PYTHON: "C:/Python36"
      TARGET: i686-pc-windows-msvc

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - pip install -r requirements.txt
  - pip install --upgrade setuptools-rust pytest pytest-benchmark wheel

build_script:
  - python -m pip -v wheel . -w .\\wheelhouse
  - dir wheelhouse

test_script:
  - python -m pip -v install fresh --no-index -f wheelhouse
  - cd ..
  - python -m pytest C:\projects\fresh\tests

artifacts:
  - path: wheelhouse\fresh*.whl