[package]
name = "fresh"
version = "0.0.1"
authors = ["Miles Granger <miles59923@gmail.com>"]

[lib]
name = "fresh"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.2.7", features = ["extension-module"]}
arrayfire = "^3.5.0"