{% set data = load_setup_py_data() %}

package:
  name: {{ package_name }}
  version: {{ data['version'] }}

source:
  path: ../

build:
  number: 1
  script:
    - pip install {{ package_name }} --no-index --no-deps -f wheelhouse


requirements:
  build:
    - python {{ python }}
    - setuptools
    - pip
  run:
    - python {{ python }}

test:
  imports:
    - {{ project_slug }}
    - {{ project_slug }}.rust.example


about:
  home: http://github.com/milesgranger/gap_statistic
  license: Apache Software License
  summary: {{ project_short_description }}